-- Pre-Approved Entry / Invite Management
-- Run this file once on your MySQL database for the configured DB_NAME.

CREATE TABLE IF NOT EXISTS pre_approved_invites (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  society_id INT NOT NULL,
  tower_id INT NULL,
  unit_id INT NULL,
  resident_id INT NOT NULL,
  invite_type ENUM('guest','cab','delivery') NOT NULL,
  invite_sub_type ENUM('quick','group','frequent','private','once') NOT NULL,
  title VARCHAR(150) NULL,
  visitor_name VARCHAR(150) NULL,
  mobile_number VARCHAR(20) NULL,
  company_name VARCHAR(150) NULL,
  vehicle_number VARCHAR(40) NULL,
  purpose VARCHAR(255) NULL,
  valid_from DATE NULL,
  valid_to DATE NULL,
  start_time TIME NULL,
  end_time TIME NULL,
  allowed_days JSON NULL,
  entries_per_day INT NULL,
  max_guest_count INT NULL,
  qr_code VARCHAR(120) NULL,
  pass_code VARCHAR(32) NULL,
  is_private TINYINT(1) NOT NULL DEFAULT 0,
  approval_required TINYINT(1) NOT NULL DEFAULT 0,
  status ENUM('draft','active','used','expired','cancelled','blocked') NOT NULL DEFAULT 'active',
  created_by INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_pai_society (society_id),
  INDEX idx_pai_resident (resident_id),
  INDEX idx_pai_type (invite_type),
  INDEX idx_pai_status (status),
  INDEX idx_pai_validity (valid_from, valid_to),
  INDEX idx_pai_pass (pass_code),
  INDEX idx_pai_qr (qr_code)
);

CREATE TABLE IF NOT EXISTS pre_approved_invite_guests (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  invite_id BIGINT NOT NULL,
  guest_name VARCHAR(150) NULL,
  mobile_number VARCHAR(20) NULL,
  vehicle_number VARCHAR(40) NULL,
  qr_code VARCHAR(120) NULL,
  pass_code VARCHAR(32) NULL,
  status ENUM('pending','checked_in','checked_out','cancelled') NOT NULL DEFAULT 'pending',
  checked_in_at DATETIME NULL,
  checked_out_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_paig_invite (invite_id),
  INDEX idx_paig_pass (pass_code),
  INDEX idx_paig_qr (qr_code),
  CONSTRAINT fk_paig_invite FOREIGN KEY (invite_id) REFERENCES pre_approved_invites(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS gate_entry_logs (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  society_id INT NOT NULL,
  gate_id INT NULL,
  invite_id BIGINT NULL,
  invite_guest_id BIGINT NULL,
  visitor_name VARCHAR(150) NULL,
  mobile_number VARCHAR(20) NULL,
  vehicle_number VARCHAR(40) NULL,
  entry_type ENUM('guest','cab','delivery') NOT NULL,
  entry_status ENUM('allowed','denied','checked_in','checked_out') NOT NULL,
  denial_reason VARCHAR(255) NULL,
  checked_in_by_guard_id INT NULL,
  checked_out_by_guard_id INT NULL,
  checked_in_at DATETIME NULL,
  checked_out_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_gel_society (society_id),
  INDEX idx_gel_invite (invite_id),
  INDEX idx_gel_invite_guest (invite_guest_id),
  INDEX idx_gel_status (entry_status),
  INDEX idx_gel_created_at (created_at),
  CONSTRAINT fk_gel_invite FOREIGN KEY (invite_id) REFERENCES pre_approved_invites(id) ON DELETE SET NULL,
  CONSTRAINT fk_gel_invite_guest FOREIGN KEY (invite_guest_id) REFERENCES pre_approved_invite_guests(id) ON DELETE SET NULL
);

