import {
  HomeIcon,
  UsersIcon,
  BuildingOfficeIcon,
  UserCircleIcon,
  WrenchIcon,
  BriefcaseIcon,
  ClipboardDocumentListIcon,
  Squares2X2Icon,
  SparklesIcon,
  TruckIcon,
  LifebuoyIcon,
  Cog6ToothIcon,
} from "@heroicons/react/24/outline";

export const menuItems = [
  {
    label: "Dashboard",
    path: "/dashboard",
    icon: HomeIcon,
  },
  {
    label: "User Management",
    path: "/user-management",
    icon: UsersIcon,
    roles: ["admin", "super-admin", "society-admin", "society-manager"],
    permission: "canManageUsers",
  },
  {
    label: "Society Management",
    path: "/society-management",
    icon: BuildingOfficeIcon,
    roles: ["admin", "super-admin", "society-admin"],
    permission: "canManageSocieties",
  },
  {
    label: "Society Admin",
    path: "/society-admin",
    icon: UserCircleIcon,
    roles: ["admin", "super-admin", "society-admin"],
    permission: "canManageUsers",
  },
  {
    label: "Services",
    path: "/services",
    icon: WrenchIcon,
    roles: ["admin", "super-admin", "society-admin", "society-manager"],
  },
  {
    label: "Services Providers",
    path: "/services-providers",
    icon: BriefcaseIcon,
    roles: ["admin", "super-admin", "society-admin", "society-manager"],
  },
  {
    label: "Service Used",
    path: "/service-used",
    icon: ClipboardDocumentListIcon,
    roles: ["admin", "super-admin", "society-admin", "society-manager"],
  },
  {
    label: "Floor Summary",
    path: "/floor-summary",
    icon: Squares2X2Icon,
    roles: ["admin", "super-admin", "society-admin", "society-manager"],
  },
  {
    label: "Amenities",
    path: "/amenities",
    icon: SparklesIcon,
    roles: [
      "admin",
      "super-admin",
      "society-admin",
      "society-manager",
      "maintenance-staff",
    ],
    permission: "canManageAmenities",
  },
  {
    label: "Parking Management",
    path: "/parking-management",
    icon: TruckIcon,
    roles: [
      "admin",
      "super-admin",
      "society-admin",
      "society-manager",
      "security-guard",
    ],
  },
  {
    label: "Support",
    path: "/support",
    icon: LifebuoyIcon,
    roles: [
      "admin",
      "super-admin",
      "society-admin",
      "society-manager",
      "help-desk",
      "security-guard",
    ],
  },
  {
    label: "Settings",
    path: "/settings",
    icon: Cog6ToothIcon,
    roles: ["admin", "super-admin"],
  },
];
